#ifndef APP_CONF_H_INCLUDED
#define APP_CONF_H_INCLUDED


#define SOFTWARE_VERSION_MAJOR  0
#define SOFTWARE_VERSION_MINOR  'A'
#define SOFTWARE_VERSION_PATCH  0


#define SOFTWARE_VERSION_HIGH (((SOFTWARE_VERSION_MAJOR & 0xFF) << 8) | (SOFTWARE_VERSION_MINOR & 0xFF))
#define SOFTWARE_VERSION_LOW SOFTWARE_VERSION_PATCH

#define SOFTWARE_BUILD_DAY 3
#define SOFTWARE_BUILD_MONTH 1
#define SOFTWARE_BUILD_YEAR 22

#define SOFTWARE_BUILD_DATE ((SOFTWARE_BUILD_DAY & 0x1F) | ((SOFTWARE_BUILD_MONTH & 0x1F) << 5) | ((SOFTWARE_BUILD_YEAR & 0x3F) << 10))


#endif